package defaultconfig

import (
	"bytes"
	_ "embed"
)

// Config contains the embedded default configuration shipped in the binary —
// the baseline every zero-config user gets. The file is generated by the build
// process (make build) from defaultConfig/.plumber.yaml, NOT from the repo-root
// .plumber.yaml (which is Plumber's own self-scan config). The two are
// independent artifacts (getplumber/plumber#352): editing Plumber's self-scan
// config never silently changes the shipped default.
//
//go:embed default.yaml
var Config []byte

// buildHeader is the comment added by 'make build' that should be stripped for user output
var buildHeader = []byte("# DO NOT EDIT - Generated from defaultConfig/.plumber.yaml by 'make build'\n")

// Get returns the embedded default configuration as a byte slice,
// with the build-time header comment stripped for clean user output.
func Get() []byte {
	// Strip the build header if present
	if bytes.HasPrefix(Config, buildHeader) {
		return Config[len(buildHeader):]
	}
	return Config
}

// GetString returns the embedded default configuration as a string,
// with the build-time header comment stripped for clean user output.
func GetString() string {
	return string(Get())
}

// GetRaw returns the raw embedded configuration including the build header.
// Use this only for debugging or internal purposes.
func GetRaw() []byte {
	return Config
}
